name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Log in to Azure using your Service Principal secrets
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      # Log Docker into your specific Azure Container Registry
      - name: Docker Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: myweatheracr26.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Build the image on the GitHub Runner and Push it to ACR
      - name: Build and Push Image
        run: |
          docker build -t myweatheracr26.azurecr.io/golang-weather-bff:${{ github.sha }} .
          docker push myweatheracr26.azurecr.io/golang-weather-bff:${{ github.sha }}
          # Also tag it as 'latest' for easier deployment later
          docker tag myweatheracr26.azurecr.io/golang-weather-bff:${{ github.sha }} myweatheracr26.azurecr.io/golang-weather-bff:latest
          docker push myweatheracr26.azurecr.io/golang-weather-bff:latest